# Generated by Django 3.0.9 on 2020-10-03 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0010_auto_20201003_1424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='twitter_url',
            new_name='linkedin_url',
        ),
    ]
