# Generated by Django 3.0.9 on 2020-10-12 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0012_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='date',
            new_name='date_added',
        ),
    ]
